import sqlite3
import csv
import os #so we can see if the db updated
from pathlib import Path
import importlib.util

class db_connectionHandler:
    # this would appear of you used db_connectionHandler.__doc__
    """
        Usage for this class "db_connectionHandler".
        *** IF CALLED AS SUBSCRIPT PUT IN with()
        It can be initialized as a subscript or ran as main.
            * if running as main or through terminal __repr__ can be used to see loaded modules
        It requires one named parameter for initialization: db_file
            - db_file: an existing SQLite db file
                If a db file does not exist at the given location
                a new one is created
        It has one built in script that creates and updates the database based on SQL defined in this file.
            - Updates occur when the source CSV is updated, or imported scripts can handle other inserts. (Update scripts should therefore update the CSV)
        Scripts are pulled from 'db_scripts/'
        If a script file is properly constructed it should populate into the object func_list
            - these will be callable as db_connectionHandler.[filename stem (without the filetype)]
            - a name: what the function is named
            - a short description
                This should look like
                    \"\"\"
                    MODULE NAME: [name of the module]
                    DESCRIPTION: [short description of what the module does]
                    USAGE: [how to use the module] <- ie list input params
                    \"\"\"
    """
    def __init__(self, db_file):
        # will add doc for this file routing
        self.csv_source = Path(__file__).resolve().parent / "db_source" / "source.csv"
        self.db_file = Path(db_file)
        self.script_folder = Path(__file__).resolve().parent / "db_scripts"
        self.mod_list = {}
        self.modules = {}
        self.recently_init = 0
        self.db_exists = False

    # These next two function allow the class to be used as a context manager with the "with" statement
    # They are constructors and destructors for the class, so the database connection is opened and closed
    # automatically when the class is used in a "with" statement.
    def __enter__(self):
        self.db_exists = self.db_file.is_file()
        self.db_file.parent.mkdir(parents=True, exist_ok=True)
        self.conn = sqlite3.connect(self.db_file)
        self.curr = self.conn.cursor()
        self.init_db()
        self._load_scripts()
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.conn.commit()
        self.conn.close()

    # This is probably not necessary
    # Desctructor for the class if missed, cleaned up on garbage collection
    def __del__(self):
        if hasattr(self , "conn") and self.conn:
            try:
                self.conn.close()
            except Exception as e:
                pass

    # Prints the content of the class, the loaded modules, and stats of its connection
    def __repr__(self):
        output = ""
        output += f"CSV_source:     {self.csv_source}\n"
        output += f"db_file:        {self.db_file}\n"
        output += f"script_folder:  {self.script_folder} Exists{self.script_folder.is_file()}\n"
        output += f"Recently init:  {self.recently_init}\n"
        
        # goes through the list of loaded modules generated by _load_scripts()
        # adds the name and metadata provided in that script to the output
        for key, value in self.mod_list.items():
            output += f"{key}: {value}\n"
        
        # adds the schema of the database to the output
        # for schema in self.curr.execute("SELECT sql FROM sqlite_schema WHERE sql NOT NULL"):
        #     output += schema[0] + "\n"
        output += "\n".join((row[0] for row in self.curr.execute("SELECT sql FROM sqlite_schema WHERE sql NOT NULL").fetchall()))
        return output
    
    # first checks if the database file exists, if not it creates it and initializes the tables
    # if the database file exists, it checks if the source CSV has been updated since the more recently than the database
    # if we decide to do so we can also update the csv instead here
    def init_db(self):
        if not self.db_exists or (self.csv_source.stat().st_mtime > self.db_file.stat().st_mtime):
            self.db_file.parent.mkdir(parents=True, exist_ok=True)
            self.db_file.touch()
            self._init_tables()
            self.recently_init = 1

    # here inputlib (what python uses for #import) is used to load the scripts from the db_scripts folder
    #   a spec is metadata of the script. like what functions are in it, what variables are in it, etc.
    #   a module is the actual script that is loaded into memory and can be called
    #   it will function just like a normal python module

    # loop iterates through the files found in the db_scripts folder
    # file_path each files file_path
    #   mod_name becomes exactly the filename without the filetype
    #   loads the module
    #   adds the module to the modules dictionary with the mod_name as the key
    #   adds the module description to the mod_list dictionary with the mod_name as the key
    def _load_scripts(self):
         for file_path in self.script_folder.glob("*.py"):
              mod_name = file_path.stem
              spec = importlib.util.spec_from_file_location(mod_name, file_path)
              module = importlib.util.module_from_spec(spec)
              spec.loader.exec_module(module)
              self.modules[mod_name] = module
              self.mod_list[mod_name] = getattr(module, 'DESCRIPTION', 'No script description.')

    # calls the scripts from above, if the script is found it will run the script and return 1, if not it will return 0
    def run_script(self , mod, *args, **kwargs):
        script_to_run = self.modules.get(mod)
        if script_to_run:
            try:
                return script_to_run.run(self.conn, *args, **kwargs)
            except Exception as e:
                print(f"Error occurred while running script '{mod}': {e}")
                return None
        return None
    
    # database creation, pretty straight forward
    def _init_tables(self):
        self.curr.execute(
            '''
            CREATE TABLE table_recipes (
                recipe_id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                description TEXT,
                instruction TEXT NOT NULL,
                prep_time INTEGER CHECK (prep_time >= 0),
                cook_time INTEGER CHECK (cook_time >= 0),
                servings INTEGER CHECK (servings >= 0),
                image_url TEXT
                ) strict;
            '''
        )
        self.curr.execute(
            '''
            CREATE TABLE table_category (
            category_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL
            ) strict;
            '''
        )
        self.curr.execute(
            '''
            CREATE TABLE table_ingredients (
            ingredient_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL UNIQUE,
            category INTEGER,
            is_staple INTEGER DEFAULT 0 CHECK (is_staple IN (0,1)),
            FOREIGN KEY (category) REFERENCES table_category (category_id)
            ) strict;
            '''
        )
        #changed quantity to REAL instead of INTEGER to handle fractional amounts
        self.curr.execute (
            '''
            CREATE TABLE recipe_ingredients (
            recipe_id INTEGER,
            ingredient_id INTEGER,
            quantity REAL CHECK (quantity >= 0),
            unit TEXT,
            is_optional INTEGER DEFAULT 0 CHECK (is_optional IN (0,1)),
            PRIMARY KEY (recipe_id,ingredient_id),
            FOREIGN KEY (recipe_id) REFERENCES table_recipes (recipe_id),
            FOREIGN KEY (ingredient_id) REFERENCES table_ingredients (ingredient_id)
            ) strict;
            '''
        )
        #added directions column
        self.curr.execute (
            '''
            CREATE TABLE table_recipe_staging (
            title TEXT NOT NULL,
            ingredients TEXT NOT NULL,
            distinct_ingredients TEXT NOT NULL,
            num_ingredients INTEGER CHECK (num_ingredients >= 0),
            link TEXT,
            source TEXT,
            directions TEXT
            )
            '''
        )

        self.conn.commit()
    
if __name__=="__main__":
    # will add doc for this file routing
    db_file = Path(__file__).resolve().parent / "db" / "db_file.db"
    debug = input("would you like to debug? (y/n)")
    with db_connectionHandler(db_file) as db:
        print("Populating database...")
        db.run_script("populate_db", db.csv_source)
        print("Database populated!")
        if debug == "y":
            print(repr(db))