title: "What's for Dinner"
description: "Dev notes and application that quickly finds recipes well-suited to ingredients users have on hand."
baseurl: "" # Keep empty for root of custom domain, or set to "/WhatsForDinner" if deployed to github.io subpath.
url: "docs/"

# Build settings
plugins:
  - jekyll-feed

exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock" , "Tech/" , "Ideas/" , "user_stories/"] 
